//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScanAnalyzer.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analis_Rules_Db
    {
        public string UUID { get; set; }
        public string Revisar { get; set; }
        public string Descripcion { get; set; }
        public string Palabra_clave { get; set; }
        public string Busqueda { get; set; }
        public string Tipo_Advertencia { get; set; }
    }
}
