//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScanAnalyzer.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analisis
    {
        public string UUID { get; set; }
        public string UUID_US { get; set; }
        public Nullable<System.DateTime> Fecha__Accion { get; set; }
        public string Tipo { get; set; }
        public string Data { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
